export enum NodeTypes {
	BODY = 'BODY',
	DIV = 'DIV',
	FORM = 'FORM',
	H1 = 'H1',
	H2 = 'H2',
	H3 = 'H3',
	H4 = 'H4',
	H5 = 'H5',
	H6 = 'H6',
	HEAD = 'HEAD',
	INPUT = 'INPUT',
	LABEL = 'LABEL',
	LI = 'LI',
	LEGEND = 'LEGEND',
	SCRIPT = 'SCRIPT',
	SELECT = 'SELECT',
	OPTION = 'OPTION',
	TABLE = 'TABLE',
	TBODY = 'TBODY',
	TEXTAREA = 'TEXTAREA',
	TD = 'TD',
	TFOOT = 'TFOOT',
	TH = 'TH',
	THEAD = 'THEAD',
	UL = 'UL',
	BUTTON = 'BUTTON',
}
