export enum ValidUiElementsNodes {
	INPUT = 'INPUT',
	CHECKBOX = 'CHECKBOX',
	RADIO = 'RADIO',
	SELECT = 'SELECT',
	TEXTAREA = 'TEXTAREA',
	BUTTON = 'BUTTON',
	TR = 'TR',
	SPAN = 'SPAN',
	EM = 'EM',
	IMG = 'IMG',
	LABEL = 'LABEL',
	STRONG = 'STRONG',
	I = 'I',
	B = 'B',
	P = 'P',
}
